### PR TITLE
Completing support for passing event_reason to XNAT CR hosts

### PR DESCRIPTION
**Pull request by bariskanber**
Following modifications by John Flavin and Baris Kanber to allow support for passing event_reason to XNAT CR hosts.

### CODE REVIEW

**Comment by johnflavin** [comment]
I think this looks good to me. I do have one change to request. Instead of merging this into the `master` branch, could you merge it into the `kwargs` branch? That way the commits we merge in would automatically be attached to the PR I have open at pyxnat/pyxnat#72.

**Comment by bariskanber** [comment]
Hi John,
Awesome, thanks. 
Do you mean I should close this pull request and create a new pull request into NrgXnat:kwargs instead?
Cheers,
Baris.

**Comment by johnflavin** [comment]
I think it may be possible to edit the one you have open to change the branch. If that isn't possible, then yes, I think you could close it and re-open it to request merging into a different branch.

**Comment by bariskanber** [comment]
Dear John,
I have changed the base branch for the merge to NrgXnat:kwargs.

Many thanks!

Baris.

**Comment by bariskanber** [comment]
Hi John,
Just wondering if you have seen the above message regarding the pull request.
Cheers,
Baris.

Mentioning @johnflavin

**Comment by johnflavin** [comment]
No, I hadn't yet seen it. Sorry about that.

**Comment by bariskanber** [comment]
Thanks John, that is awesome. Will we also need to merge NrgXnat:kwargs into the mainstream pyxnat?

We are doing similar modifications to DAX (to make it XNAT CR compatible) and I presume we will need a new version number for pyxnat that can be added as a requirement for the new DAX version.

**Comment by johnflavin** [comment]
Yes, the next step is to get the changes merged into pyxnat and get a new release. But I don't know who is minding the shop over there.

**Comment by bariskanber** [comment]
Any ideas how to go about it? You already seem to have a pull request open but hasn't been responded to. Do we need to tag some people?

**Comment by johnflavin** [comment]
We've released a new version, 1.0.1.0. See if you can pull it from pypi.

**Comment by bariskanber** [comment]
Hi John, I ran the following command and was seemingly able to upgrade correctly.
pip install pyxnat --upgrade

Many thanks for all your help.

**Pull request merged**
